// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.medizin.osce.domain;

import ch.unibas.medizin.osce.domain.AnamnesisCheckTitle;
import java.lang.Integer;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AnamnesisCheckTitleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AnamnesisCheckTitleDataOnDemand: @Component;
    
    private Random AnamnesisCheckTitleDataOnDemand.rnd = new SecureRandom();
    
    private List<AnamnesisCheckTitle> AnamnesisCheckTitleDataOnDemand.data;
    
    public AnamnesisCheckTitle AnamnesisCheckTitleDataOnDemand.getNewTransientAnamnesisCheckTitle(int index) {
        AnamnesisCheckTitle obj = new AnamnesisCheckTitle();
        setSort_order(obj, index);
        setText(obj, index);
        return obj;
    }
    
    public void AnamnesisCheckTitleDataOnDemand.setSort_order(AnamnesisCheckTitle obj, int index) {
        Integer sort_order = new Integer(index);
        obj.setSort_order(sort_order);
    }
    
    public void AnamnesisCheckTitleDataOnDemand.setText(AnamnesisCheckTitle obj, int index) {
        String text = "text_" + index;
        if (text.length() > 255) {
            text = text.substring(0, 255);
        }
        obj.setText(text);
    }
    
    public AnamnesisCheckTitle AnamnesisCheckTitleDataOnDemand.getSpecificAnamnesisCheckTitle(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        AnamnesisCheckTitle obj = data.get(index);
        return AnamnesisCheckTitle.findAnamnesisCheckTitle(obj.getId());
    }
    
    public AnamnesisCheckTitle AnamnesisCheckTitleDataOnDemand.getRandomAnamnesisCheckTitle() {
        init();
        AnamnesisCheckTitle obj = data.get(rnd.nextInt(data.size()));
        return AnamnesisCheckTitle.findAnamnesisCheckTitle(obj.getId());
    }
    
    public boolean AnamnesisCheckTitleDataOnDemand.modifyAnamnesisCheckTitle(AnamnesisCheckTitle obj) {
        return false;
    }
    
    public void AnamnesisCheckTitleDataOnDemand.init() {
        data = AnamnesisCheckTitle.findAnamnesisCheckTitleEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'AnamnesisCheckTitle' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ch.unibas.medizin.osce.domain.AnamnesisCheckTitle>();
        for (int i = 0; i < 10; i++) {
            AnamnesisCheckTitle obj = getNewTransientAnamnesisCheckTitle(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
