// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.medizin.osce.domain;

import ch.unibas.medizin.osce.domain.ClinicDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClinicIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClinicIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClinicIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ClinicIntegrationTest: @Transactional;
    
    @Autowired
    private ClinicDataOnDemand ClinicIntegrationTest.dod;
    
    @Test
    public void ClinicIntegrationTest.testCountClinics() {
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to initialize correctly", dod.getRandomClinic());
        long count = ch.unibas.medizin.osce.domain.Clinic.countClinics();
        org.junit.Assert.assertTrue("Counter for 'Clinic' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClinicIntegrationTest.testFindClinic() {
        ch.unibas.medizin.osce.domain.Clinic obj = dod.getRandomClinic();
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Clinic.findClinic(id);
        org.junit.Assert.assertNotNull("Find method for 'Clinic' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Clinic' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClinicIntegrationTest.testFindAllClinics() {
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to initialize correctly", dod.getRandomClinic());
        long count = ch.unibas.medizin.osce.domain.Clinic.countClinics();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Clinic', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<ch.unibas.medizin.osce.domain.Clinic> result = ch.unibas.medizin.osce.domain.Clinic.findAllClinics();
        org.junit.Assert.assertNotNull("Find all method for 'Clinic' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Clinic' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClinicIntegrationTest.testFindClinicEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to initialize correctly", dod.getRandomClinic());
        long count = ch.unibas.medizin.osce.domain.Clinic.countClinics();
        if (count > 20) count = 20;
        java.util.List<ch.unibas.medizin.osce.domain.Clinic> result = ch.unibas.medizin.osce.domain.Clinic.findClinicEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Clinic' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Clinic' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClinicIntegrationTest.testFlush() {
        ch.unibas.medizin.osce.domain.Clinic obj = dod.getRandomClinic();
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Clinic.findClinic(id);
        org.junit.Assert.assertNotNull("Find method for 'Clinic' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClinic(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Clinic' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClinicIntegrationTest.testMerge() {
        ch.unibas.medizin.osce.domain.Clinic obj = dod.getRandomClinic();
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Clinic.findClinic(id);
        boolean modified =  dod.modifyClinic(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        ch.unibas.medizin.osce.domain.Clinic merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Clinic' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClinicIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to initialize correctly", dod.getRandomClinic());
        ch.unibas.medizin.osce.domain.Clinic obj = dod.getNewTransientClinic(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Clinic' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Clinic' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClinicIntegrationTest.testRemove() {
        ch.unibas.medizin.osce.domain.Clinic obj = dod.getRandomClinic();
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Clinic' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Clinic.findClinic(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Clinic' with identifier '" + id + "'", ch.unibas.medizin.osce.domain.Clinic.findClinic(id));
    }
    
}
