// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.medizin.osce.domain;

import ch.unibas.medizin.osce.domain.EliminationCriterionDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EliminationCriterionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EliminationCriterionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EliminationCriterionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: EliminationCriterionIntegrationTest: @Transactional;
    
    @Autowired
    private EliminationCriterionDataOnDemand EliminationCriterionIntegrationTest.dod;
    
    @Test
    public void EliminationCriterionIntegrationTest.testCountEliminationCriterions() {
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to initialize correctly", dod.getRandomEliminationCriterion());
        long count = ch.unibas.medizin.osce.domain.EliminationCriterion.countEliminationCriterions();
        org.junit.Assert.assertTrue("Counter for 'EliminationCriterion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EliminationCriterionIntegrationTest.testFindEliminationCriterion() {
        ch.unibas.medizin.osce.domain.EliminationCriterion obj = dod.getRandomEliminationCriterion();
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.EliminationCriterion.findEliminationCriterion(id);
        org.junit.Assert.assertNotNull("Find method for 'EliminationCriterion' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'EliminationCriterion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EliminationCriterionIntegrationTest.testFindAllEliminationCriterions() {
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to initialize correctly", dod.getRandomEliminationCriterion());
        long count = ch.unibas.medizin.osce.domain.EliminationCriterion.countEliminationCriterions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'EliminationCriterion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<ch.unibas.medizin.osce.domain.EliminationCriterion> result = ch.unibas.medizin.osce.domain.EliminationCriterion.findAllEliminationCriterions();
        org.junit.Assert.assertNotNull("Find all method for 'EliminationCriterion' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'EliminationCriterion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EliminationCriterionIntegrationTest.testFindEliminationCriterionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to initialize correctly", dod.getRandomEliminationCriterion());
        long count = ch.unibas.medizin.osce.domain.EliminationCriterion.countEliminationCriterions();
        if (count > 20) count = 20;
        java.util.List<ch.unibas.medizin.osce.domain.EliminationCriterion> result = ch.unibas.medizin.osce.domain.EliminationCriterion.findEliminationCriterionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'EliminationCriterion' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'EliminationCriterion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EliminationCriterionIntegrationTest.testFlush() {
        ch.unibas.medizin.osce.domain.EliminationCriterion obj = dod.getRandomEliminationCriterion();
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.EliminationCriterion.findEliminationCriterion(id);
        org.junit.Assert.assertNotNull("Find method for 'EliminationCriterion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEliminationCriterion(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'EliminationCriterion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EliminationCriterionIntegrationTest.testMerge() {
        ch.unibas.medizin.osce.domain.EliminationCriterion obj = dod.getRandomEliminationCriterion();
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.EliminationCriterion.findEliminationCriterion(id);
        boolean modified =  dod.modifyEliminationCriterion(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        ch.unibas.medizin.osce.domain.EliminationCriterion merged = (ch.unibas.medizin.osce.domain.EliminationCriterion) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'EliminationCriterion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EliminationCriterionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to initialize correctly", dod.getRandomEliminationCriterion());
        ch.unibas.medizin.osce.domain.EliminationCriterion obj = dod.getNewTransientEliminationCriterion(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'EliminationCriterion' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'EliminationCriterion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EliminationCriterionIntegrationTest.testRemove() {
        ch.unibas.medizin.osce.domain.EliminationCriterion obj = dod.getRandomEliminationCriterion();
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'EliminationCriterion' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.EliminationCriterion.findEliminationCriterion(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'EliminationCriterion' with identifier '" + id + "'", ch.unibas.medizin.osce.domain.EliminationCriterion.findEliminationCriterion(id));
    }
    
}
