// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.medizin.osce.domain;

import ch.unibas.medizin.osce.domain.LangSkillDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LangSkillIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LangSkillIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LangSkillIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: LangSkillIntegrationTest: @Transactional;
    
    @Autowired
    private LangSkillDataOnDemand LangSkillIntegrationTest.dod;
    
    @Test
    public void LangSkillIntegrationTest.testCountLangSkills() {
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to initialize correctly", dod.getRandomLangSkill());
        long count = ch.unibas.medizin.osce.domain.LangSkill.countLangSkills();
        org.junit.Assert.assertTrue("Counter for 'LangSkill' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LangSkillIntegrationTest.testFindLangSkill() {
        ch.unibas.medizin.osce.domain.LangSkill obj = dod.getRandomLangSkill();
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.LangSkill.findLangSkill(id);
        org.junit.Assert.assertNotNull("Find method for 'LangSkill' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'LangSkill' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LangSkillIntegrationTest.testFindAllLangSkills() {
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to initialize correctly", dod.getRandomLangSkill());
        long count = ch.unibas.medizin.osce.domain.LangSkill.countLangSkills();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'LangSkill', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<ch.unibas.medizin.osce.domain.LangSkill> result = ch.unibas.medizin.osce.domain.LangSkill.findAllLangSkills();
        org.junit.Assert.assertNotNull("Find all method for 'LangSkill' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'LangSkill' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LangSkillIntegrationTest.testFindLangSkillEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to initialize correctly", dod.getRandomLangSkill());
        long count = ch.unibas.medizin.osce.domain.LangSkill.countLangSkills();
        if (count > 20) count = 20;
        java.util.List<ch.unibas.medizin.osce.domain.LangSkill> result = ch.unibas.medizin.osce.domain.LangSkill.findLangSkillEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'LangSkill' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'LangSkill' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LangSkillIntegrationTest.testFlush() {
        ch.unibas.medizin.osce.domain.LangSkill obj = dod.getRandomLangSkill();
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.LangSkill.findLangSkill(id);
        org.junit.Assert.assertNotNull("Find method for 'LangSkill' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLangSkill(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'LangSkill' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LangSkillIntegrationTest.testMerge() {
        ch.unibas.medizin.osce.domain.LangSkill obj = dod.getRandomLangSkill();
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.LangSkill.findLangSkill(id);
        boolean modified =  dod.modifyLangSkill(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        ch.unibas.medizin.osce.domain.LangSkill merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'LangSkill' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LangSkillIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to initialize correctly", dod.getRandomLangSkill());
        ch.unibas.medizin.osce.domain.LangSkill obj = dod.getNewTransientLangSkill(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'LangSkill' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'LangSkill' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LangSkillIntegrationTest.testRemove() {
        ch.unibas.medizin.osce.domain.LangSkill obj = dod.getRandomLangSkill();
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'LangSkill' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.LangSkill.findLangSkill(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'LangSkill' with identifier '" + id + "'", ch.unibas.medizin.osce.domain.LangSkill.findLangSkill(id));
    }
    
}
