// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.medizin.osce.domain;

import ch.unibas.medizin.osce.domain.Nationality;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect NationalityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NationalityDataOnDemand: @Component;
    
    private Random NationalityDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Nationality> NationalityDataOnDemand.data;
    
    public Nationality NationalityDataOnDemand.getNewTransientNationality(int index) {
        ch.unibas.medizin.osce.domain.Nationality obj = new ch.unibas.medizin.osce.domain.Nationality();
        setNationality(obj, index);
        return obj;
    }
    
    private void NationalityDataOnDemand.setNationality(Nationality obj, int index) {
        java.lang.String nationality = "nationality_" + index;
        if (nationality.length() > 40) {
            nationality = nationality.substring(0, 40);
        }
        obj.setNationality(nationality);
    }
    
    public Nationality NationalityDataOnDemand.getSpecificNationality(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Nationality obj = data.get(index);
        return Nationality.findNationality(obj.getId());
    }
    
    public Nationality NationalityDataOnDemand.getRandomNationality() {
        init();
        Nationality obj = data.get(rnd.nextInt(data.size()));
        return Nationality.findNationality(obj.getId());
    }
    
    public boolean NationalityDataOnDemand.modifyNationality(Nationality obj) {
        return false;
    }
    
    public void NationalityDataOnDemand.init() {
        data = ch.unibas.medizin.osce.domain.Nationality.findNationalityEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Nationality' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<ch.unibas.medizin.osce.domain.Nationality>();
        for (int i = 0; i < 10; i++) {
            ch.unibas.medizin.osce.domain.Nationality obj = getNewTransientNationality(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
