// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.medizin.osce.domain;

import ch.unibas.medizin.osce.domain.ScarDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ScarIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ScarIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ScarIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ScarIntegrationTest: @Transactional;
    
    @Autowired
    private ScarDataOnDemand ScarIntegrationTest.dod;
    
    @Test
    public void ScarIntegrationTest.testCountScars() {
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to initialize correctly", dod.getRandomScar());
        long count = ch.unibas.medizin.osce.domain.Scar.countScars();
        org.junit.Assert.assertTrue("Counter for 'Scar' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ScarIntegrationTest.testFindScar() {
        ch.unibas.medizin.osce.domain.Scar obj = dod.getRandomScar();
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Scar.findScar(id);
        org.junit.Assert.assertNotNull("Find method for 'Scar' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Scar' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ScarIntegrationTest.testFindAllScars() {
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to initialize correctly", dod.getRandomScar());
        long count = ch.unibas.medizin.osce.domain.Scar.countScars();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Scar', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<ch.unibas.medizin.osce.domain.Scar> result = ch.unibas.medizin.osce.domain.Scar.findAllScars();
        org.junit.Assert.assertNotNull("Find all method for 'Scar' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Scar' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ScarIntegrationTest.testFindScarEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to initialize correctly", dod.getRandomScar());
        long count = ch.unibas.medizin.osce.domain.Scar.countScars();
        if (count > 20) count = 20;
        java.util.List<ch.unibas.medizin.osce.domain.Scar> result = ch.unibas.medizin.osce.domain.Scar.findScarEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Scar' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Scar' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ScarIntegrationTest.testFlush() {
        ch.unibas.medizin.osce.domain.Scar obj = dod.getRandomScar();
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Scar.findScar(id);
        org.junit.Assert.assertNotNull("Find method for 'Scar' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyScar(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Scar' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ScarIntegrationTest.testMerge() {
        ch.unibas.medizin.osce.domain.Scar obj = dod.getRandomScar();
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Scar.findScar(id);
        boolean modified =  dod.modifyScar(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        ch.unibas.medizin.osce.domain.Scar merged = (ch.unibas.medizin.osce.domain.Scar) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Scar' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ScarIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to initialize correctly", dod.getRandomScar());
        ch.unibas.medizin.osce.domain.Scar obj = dod.getNewTransientScar(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Scar' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Scar' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ScarIntegrationTest.testRemove() {
        ch.unibas.medizin.osce.domain.Scar obj = dod.getRandomScar();
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Scar' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Scar.findScar(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Scar' with identifier '" + id + "'", ch.unibas.medizin.osce.domain.Scar.findScar(id));
    }
    
}
