// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.medizin.osce.domain;

import ch.unibas.medizin.osce.domain.SpecialisationDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SpecialisationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SpecialisationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SpecialisationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SpecialisationIntegrationTest: @Transactional;
    
    @Autowired
    private SpecialisationDataOnDemand SpecialisationIntegrationTest.dod;
    
    @Test
    public void SpecialisationIntegrationTest.testCountSpecialisations() {
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to initialize correctly", dod.getRandomSpecialisation());
        long count = ch.unibas.medizin.osce.domain.Specialisation.countSpecialisations();
        org.junit.Assert.assertTrue("Counter for 'Specialisation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SpecialisationIntegrationTest.testFindSpecialisation() {
        ch.unibas.medizin.osce.domain.Specialisation obj = dod.getRandomSpecialisation();
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Specialisation.findSpecialisation(id);
        org.junit.Assert.assertNotNull("Find method for 'Specialisation' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Specialisation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SpecialisationIntegrationTest.testFindAllSpecialisations() {
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to initialize correctly", dod.getRandomSpecialisation());
        long count = ch.unibas.medizin.osce.domain.Specialisation.countSpecialisations();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Specialisation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<ch.unibas.medizin.osce.domain.Specialisation> result = ch.unibas.medizin.osce.domain.Specialisation.findAllSpecialisations();
        org.junit.Assert.assertNotNull("Find all method for 'Specialisation' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Specialisation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SpecialisationIntegrationTest.testFindSpecialisationEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to initialize correctly", dod.getRandomSpecialisation());
        long count = ch.unibas.medizin.osce.domain.Specialisation.countSpecialisations();
        if (count > 20) count = 20;
        java.util.List<ch.unibas.medizin.osce.domain.Specialisation> result = ch.unibas.medizin.osce.domain.Specialisation.findSpecialisationEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Specialisation' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Specialisation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SpecialisationIntegrationTest.testFlush() {
        ch.unibas.medizin.osce.domain.Specialisation obj = dod.getRandomSpecialisation();
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Specialisation.findSpecialisation(id);
        org.junit.Assert.assertNotNull("Find method for 'Specialisation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySpecialisation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Specialisation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SpecialisationIntegrationTest.testMerge() {
        ch.unibas.medizin.osce.domain.Specialisation obj = dod.getRandomSpecialisation();
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Specialisation.findSpecialisation(id);
        boolean modified =  dod.modifySpecialisation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        ch.unibas.medizin.osce.domain.Specialisation merged = (ch.unibas.medizin.osce.domain.Specialisation) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Specialisation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SpecialisationIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to initialize correctly", dod.getRandomSpecialisation());
        ch.unibas.medizin.osce.domain.Specialisation obj = dod.getNewTransientSpecialisation(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Specialisation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Specialisation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SpecialisationIntegrationTest.testRemove() {
        ch.unibas.medizin.osce.domain.Specialisation obj = dod.getRandomSpecialisation();
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Specialisation' failed to provide an identifier", id);
        obj = ch.unibas.medizin.osce.domain.Specialisation.findSpecialisation(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Specialisation' with identifier '" + id + "'", ch.unibas.medizin.osce.domain.Specialisation.findSpecialisation(id));
    }
    
}
