// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.activity;

import ch.unibas.medizin.osce.client.managed.activity.AssignmentEditActivityWrapper.View;
import ch.unibas.medizin.osce.client.managed.request.ApplicationRequestFactory;
import ch.unibas.medizin.osce.client.managed.request.AssignmentProxy;
import ch.unibas.medizin.osce.client.managed.request.DoctorProxy;
import ch.unibas.medizin.osce.client.managed.request.OsceDayProxy;
import ch.unibas.medizin.osce.client.managed.request.OscePostRoomProxy;
import ch.unibas.medizin.osce.client.managed.request.PatientInRoleProxy;
import ch.unibas.medizin.osce.client.managed.request.StudentProxy;
import ch.unibas.medizin.osce.client.scaffold.activity.IsScaffoldMobileActivity;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyListPlace;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyPlace;
import ch.unibas.medizin.osce.shared.AssignmentTypes;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

public abstract class AssignmentEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setTypePickerValues(Arrays.asList(AssignmentTypes.values()));
        view.setOsceDayPickerValues(Collections.<OsceDayProxy>emptyList());
        requests.osceDayRequest().findOsceDayEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.OsceDayProxyRenderer.instance().getPaths()).fire(new Receiver<List<OsceDayProxy>>() {

            public void onSuccess(List<OsceDayProxy> response) {
                List<OsceDayProxy> values = new ArrayList<OsceDayProxy>();
                values.add(null);
                values.addAll(response);
                view.setOsceDayPickerValues(values);
            }
        });
        view.setOscePostRoomPickerValues(Collections.<OscePostRoomProxy>emptyList());
        requests.oscePostRoomRequest().findOscePostRoomEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.OscePostRoomProxyRenderer.instance().getPaths()).fire(new Receiver<List<OscePostRoomProxy>>() {

            public void onSuccess(List<OscePostRoomProxy> response) {
                List<OscePostRoomProxy> values = new ArrayList<OscePostRoomProxy>();
                values.add(null);
                values.addAll(response);
                view.setOscePostRoomPickerValues(values);
            }
        });
        view.setStudentPickerValues(Collections.<StudentProxy>emptyList());
        requests.studentRequest().findStudentEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.StudentProxyRenderer.instance().getPaths()).fire(new Receiver<List<StudentProxy>>() {

            public void onSuccess(List<StudentProxy> response) {
                List<StudentProxy> values = new ArrayList<StudentProxy>();
                values.add(null);
                values.addAll(response);
                view.setStudentPickerValues(values);
            }
        });
        view.setPatientInRolePickerValues(Collections.<PatientInRoleProxy>emptyList());
        requests.patientInRoleRequest().findPatientInRoleEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.PatientInRoleProxyRenderer.instance().getPaths()).fire(new Receiver<List<PatientInRoleProxy>>() {

            public void onSuccess(List<PatientInRoleProxy> response) {
                List<PatientInRoleProxy> values = new ArrayList<PatientInRoleProxy>();
                values.add(null);
                values.addAll(response);
                view.setPatientInRolePickerValues(values);
            }
        });
        view.setExaminerPickerValues(Collections.<DoctorProxy>emptyList());
        requests.doctorRequest().findDoctorEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.DoctorProxyRenderer.instance().getPaths()).fire(new Receiver<List<DoctorProxy>>() {

            public void onSuccess(List<DoctorProxy> response) {
                List<DoctorProxy> values = new ArrayList<DoctorProxy>();
                values.add(null);
                values.addAll(response);
                view.setExaminerPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView<ch.unibas.medizin.osce.client.managed.request.AssignmentProxy, V>> extends ProxyEditView<AssignmentProxy, V> {

        void setTypePickerValues(Collection<AssignmentTypes> values);

        void setOsceDayPickerValues(Collection<OsceDayProxy> values);

        void setOscePostRoomPickerValues(Collection<OscePostRoomProxy> values);

        void setStudentPickerValues(Collection<StudentProxy> values);

        void setPatientInRolePickerValues(Collection<PatientInRoleProxy> values);

        void setExaminerPickerValues(Collection<DoctorProxy> values);
    }
}
