// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.activity;

import ch.unibas.medizin.osce.client.managed.activity.OscePostEditActivityWrapper.View;
import ch.unibas.medizin.osce.client.managed.request.ApplicationRequestFactory;
import ch.unibas.medizin.osce.client.managed.request.OscePostBlueprintProxy;
import ch.unibas.medizin.osce.client.managed.request.OscePostProxy;
import ch.unibas.medizin.osce.client.managed.request.OscePostRoomProxy;
import ch.unibas.medizin.osce.client.managed.request.OsceSequenceProxy;
import ch.unibas.medizin.osce.client.managed.request.PatientInRoleProxy;
import ch.unibas.medizin.osce.client.managed.request.StandardizedRoleProxy;
import ch.unibas.medizin.osce.client.managed.ui.OscePostRoomSetEditor;
import ch.unibas.medizin.osce.client.managed.ui.PatientInRoleSetEditor;
import ch.unibas.medizin.osce.client.scaffold.activity.IsScaffoldMobileActivity;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyListPlace;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;

public abstract class OscePostEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setOscePostBlueprintPickerValues(Collections.<OscePostBlueprintProxy>emptyList());
        requests.oscePostBlueprintRequest().findOscePostBlueprintEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.OscePostBlueprintProxyRenderer.instance().getPaths()).fire(new Receiver<List<OscePostBlueprintProxy>>() {

            public void onSuccess(List<OscePostBlueprintProxy> response) {
                List<OscePostBlueprintProxy> values = new ArrayList<OscePostBlueprintProxy>();
                values.add(null);
                values.addAll(response);
                view.setOscePostBlueprintPickerValues(values);
            }
        });
        view.setOscePostRoomsPickerValues(Collections.<OscePostRoomProxy>emptyList());
        requests.oscePostRoomRequest().findOscePostRoomEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.OscePostRoomProxyRenderer.instance().getPaths()).fire(new Receiver<List<OscePostRoomProxy>>() {

            public void onSuccess(List<OscePostRoomProxy> response) {
                List<OscePostRoomProxy> values = new ArrayList<OscePostRoomProxy>();
                values.add(null);
                values.addAll(response);
                view.setOscePostRoomsPickerValues(values);
            }
        });
        view.setPatientInRolePickerValues(Collections.<PatientInRoleProxy>emptyList());
        requests.patientInRoleRequest().findPatientInRoleEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.PatientInRoleProxyRenderer.instance().getPaths()).fire(new Receiver<List<PatientInRoleProxy>>() {

            public void onSuccess(List<PatientInRoleProxy> response) {
                List<PatientInRoleProxy> values = new ArrayList<PatientInRoleProxy>();
                values.add(null);
                values.addAll(response);
                view.setPatientInRolePickerValues(values);
            }
        });
        view.setStandardizedRolePickerValues(Collections.<StandardizedRoleProxy>emptyList());
        requests.standardizedRoleRequest().findStandardizedRoleEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.StandardizedRoleProxyRenderer.instance().getPaths()).fire(new Receiver<List<StandardizedRoleProxy>>() {

            public void onSuccess(List<StandardizedRoleProxy> response) {
                List<StandardizedRoleProxy> values = new ArrayList<StandardizedRoleProxy>();
                values.add(null);
                values.addAll(response);
                view.setStandardizedRolePickerValues(values);
            }
        });
        view.setOsceSequencePickerValues(Collections.<OsceSequenceProxy>emptyList());
        requests.osceSequenceRequest().findOsceSequenceEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.OsceSequenceProxyRenderer.instance().getPaths()).fire(new Receiver<List<OsceSequenceProxy>>() {

            public void onSuccess(List<OsceSequenceProxy> response) {
                List<OsceSequenceProxy> values = new ArrayList<OsceSequenceProxy>();
                values.add(null);
                values.addAll(response);
                view.setOsceSequencePickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView<ch.unibas.medizin.osce.client.managed.request.OscePostProxy, V>> extends ProxyEditView<OscePostProxy, V> {

        void setOscePostBlueprintPickerValues(Collection<OscePostBlueprintProxy> values);

        void setOscePostRoomsPickerValues(Collection<OscePostRoomProxy> values);

        void setPatientInRolePickerValues(Collection<PatientInRoleProxy> values);

        void setStandardizedRolePickerValues(Collection<StandardizedRoleProxy> values);

        void setOsceSequencePickerValues(Collection<OsceSequenceProxy> values);
    }
}
