// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.activity;

import ch.unibas.medizin.osce.client.managed.activity.OsceEditActivityWrapper.View;
import ch.unibas.medizin.osce.client.managed.request.ApplicationRequestFactory;
import ch.unibas.medizin.osce.client.managed.request.CourseProxy;
import ch.unibas.medizin.osce.client.managed.request.OsceDayProxy;
import ch.unibas.medizin.osce.client.managed.request.OsceProxy;
import ch.unibas.medizin.osce.client.managed.request.SemesterProxy;
import ch.unibas.medizin.osce.client.managed.request.StudentProxy;
import ch.unibas.medizin.osce.client.managed.ui.CourseSetEditor;
import ch.unibas.medizin.osce.client.managed.ui.OsceDaySetEditor;
import ch.unibas.medizin.osce.client.managed.ui.StudentSetEditor;
import ch.unibas.medizin.osce.client.scaffold.activity.IsScaffoldMobileActivity;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyListPlace;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyPlace;
import ch.unibas.medizin.osce.shared.StudyYears;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;

public abstract class OsceEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setStudyYearPickerValues(Arrays.asList(StudyYears.values()));
        view.setSemesterPickerValues(Collections.<SemesterProxy>emptyList());
        requests.semesterRequest().findSemesterEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.SemesterProxyRenderer.instance().getPaths()).fire(new Receiver<List<SemesterProxy>>() {

            public void onSuccess(List<SemesterProxy> response) {
                List<SemesterProxy> values = new ArrayList<SemesterProxy>();
                values.add(null);
                values.addAll(response);
                view.setSemesterPickerValues(values);
            }
        });
        view.setOsce_daysPickerValues(Collections.<OsceDayProxy>emptyList());
        requests.osceDayRequest().findOsceDayEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.OsceDayProxyRenderer.instance().getPaths()).fire(new Receiver<List<OsceDayProxy>>() {

            public void onSuccess(List<OsceDayProxy> response) {
                List<OsceDayProxy> values = new ArrayList<OsceDayProxy>();
                values.add(null);
                values.addAll(response);
                view.setOsce_daysPickerValues(values);
            }
        });
        view.setCoursesPickerValues(Collections.<CourseProxy>emptyList());
        requests.courseRequest().findCourseEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.CourseProxyRenderer.instance().getPaths()).fire(new Receiver<List<CourseProxy>>() {

            public void onSuccess(List<CourseProxy> response) {
                List<CourseProxy> values = new ArrayList<CourseProxy>();
                values.add(null);
                values.addAll(response);
                view.setCoursesPickerValues(values);
            }
        });
        view.setStudentsPickerValues(Collections.<StudentProxy>emptyList());
        requests.studentRequest().findStudentEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.StudentProxyRenderer.instance().getPaths()).fire(new Receiver<List<StudentProxy>>() {

            public void onSuccess(List<StudentProxy> response) {
                List<StudentProxy> values = new ArrayList<StudentProxy>();
                values.add(null);
                values.addAll(response);
                view.setStudentsPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView<ch.unibas.medizin.osce.client.managed.request.OsceProxy, V>> extends ProxyEditView<OsceProxy, V> {

        void setStudyYearPickerValues(Collection<StudyYears> values);

        void setSemesterPickerValues(Collection<SemesterProxy> values);

        void setOsce_daysPickerValues(Collection<OsceDayProxy> values);

        void setCoursesPickerValues(Collection<CourseProxy> values);

        void setStudentsPickerValues(Collection<StudentProxy> values);
    }
}
