// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.activity;

import ch.unibas.medizin.osce.client.managed.activity.RoleTableItemEditActivityWrapper.View;
import ch.unibas.medizin.osce.client.managed.request.ApplicationRequestFactory;
import ch.unibas.medizin.osce.client.managed.request.RoleBaseItemProxy;
import ch.unibas.medizin.osce.client.managed.request.RoleTableItemProxy;
import ch.unibas.medizin.osce.client.managed.request.RoleTableItemValueProxy;
import ch.unibas.medizin.osce.client.managed.ui.RoleTableItemValueSetEditor;
import ch.unibas.medizin.osce.client.scaffold.activity.IsScaffoldMobileActivity;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyListPlace;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Set;

public abstract class RoleTableItemEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setRoleBaseItemPickerValues(Collections.<RoleBaseItemProxy>emptyList());
        requests.roleBaseItemRequest().findRoleBaseItemEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.RoleBaseItemProxyRenderer.instance().getPaths()).fire(new Receiver<List<RoleBaseItemProxy>>() {

            public void onSuccess(List<RoleBaseItemProxy> response) {
                List<RoleBaseItemProxy> values = new ArrayList<RoleBaseItemProxy>();
                values.add(null);
                values.addAll(response);
                view.setRoleBaseItemPickerValues(values);
            }
        });
        view.setRoleTableItemValuePickerValues(Collections.<RoleTableItemValueProxy>emptyList());
        requests.roleTableItemValueRequest().findRoleTableItemValueEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.RoleTableItemValueProxyRenderer.instance().getPaths()).fire(new Receiver<List<RoleTableItemValueProxy>>() {

            public void onSuccess(List<RoleTableItemValueProxy> response) {
                List<RoleTableItemValueProxy> values = new ArrayList<RoleTableItemValueProxy>();
                values.add(null);
                values.addAll(response);
                view.setRoleTableItemValuePickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView<ch.unibas.medizin.osce.client.managed.request.RoleTableItemProxy, V>> extends ProxyEditView<RoleTableItemProxy, V> {

        void setRoleBaseItemPickerValues(Collection<RoleBaseItemProxy> values);

        void setRoleTableItemValuePickerValues(Collection<RoleTableItemValueProxy> values);
    }
}
