// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.activity;

import ch.unibas.medizin.osce.client.managed.activity.StandardizedRoleEditActivityWrapper.View;
import ch.unibas.medizin.osce.client.managed.request.ApplicationRequestFactory;
import ch.unibas.medizin.osce.client.managed.request.DoctorProxy;
import ch.unibas.medizin.osce.client.managed.request.RoleTopicProxy;
import ch.unibas.medizin.osce.client.managed.request.StandardizedRoleProxy;
import ch.unibas.medizin.osce.client.scaffold.activity.IsScaffoldMobileActivity;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyListPlace;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

public abstract class StandardizedRoleEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setRoleTopicPickerValues(Collections.<RoleTopicProxy>emptyList());
        requests.roleTopicRequest().findRoleTopicEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.RoleTopicProxyRenderer.instance().getPaths()).fire(new Receiver<List<RoleTopicProxy>>() {

            public void onSuccess(List<RoleTopicProxy> response) {
                List<RoleTopicProxy> values = new ArrayList<RoleTopicProxy>();
                values.add(null);
                values.addAll(response);
                view.setRoleTopicPickerValues(values);
            }
        });
        view.setAuthorPickerValues(Collections.<DoctorProxy>emptyList());
        requests.doctorRequest().findDoctorEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.DoctorProxyRenderer.instance().getPaths()).fire(new Receiver<List<DoctorProxy>>() {

            public void onSuccess(List<DoctorProxy> response) {
                List<DoctorProxy> values = new ArrayList<DoctorProxy>();
                values.add(null);
                values.addAll(response);
                view.setAuthorPickerValues(values);
            }
        });
        view.setReviewerPickerValues(Collections.<DoctorProxy>emptyList());
        requests.doctorRequest().findDoctorEntries(0, 50).with(ch.unibas.medizin.osce.client.managed.ui.DoctorProxyRenderer.instance().getPaths()).fire(new Receiver<List<DoctorProxy>>() {

            public void onSuccess(List<DoctorProxy> response) {
                List<DoctorProxy> values = new ArrayList<DoctorProxy>();
                values.add(null);
                values.addAll(response);
                view.setReviewerPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends ch.unibas.medizin.osce.client.scaffold.place.ProxyEditView<ch.unibas.medizin.osce.client.managed.request.StandardizedRoleProxy, V>> extends ProxyEditView<StandardizedRoleProxy, V> {

        void setRoleTopicPickerValues(Collection<RoleTopicProxy> values);

        void setAuthorPickerValues(Collection<DoctorProxy> values);

        void setReviewerPickerValues(Collection<DoctorProxy> values);
    }
}
