// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.ui;

import ch.unibas.medizin.osce.client.managed.request.CheckListProxy;
import ch.unibas.medizin.osce.client.managed.request.ChecklistQuestionProxy;
import ch.unibas.medizin.osce.client.managed.request.ChecklistTopicProxy;
import ch.unibas.medizin.osce.client.scaffold.place.AbstractProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public abstract class ChecklistTopicListView_Roo_Gwt extends AbstractProxyListView<ChecklistTopicProxy> {

    @UiField
    CellTable<ChecklistTopicProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<ChecklistTopicProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ChecklistTopicProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("version");
        table.addColumn(new TextColumn<ChecklistTopicProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ChecklistTopicProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
        paths.add("sort_order");
        table.addColumn(new TextColumn<ChecklistTopicProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ChecklistTopicProxy object) {
                return renderer.render(object.getSort_order());
            }
        }, "Sort_order");
        paths.add("title");
        table.addColumn(new TextColumn<ChecklistTopicProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ChecklistTopicProxy object) {
                return renderer.render(object.getTitle());
            }
        }, "Title");
        paths.add("checkList");
        table.addColumn(new TextColumn<ChecklistTopicProxy>() {

            Renderer<ch.unibas.medizin.osce.client.managed.request.CheckListProxy> renderer = ch.unibas.medizin.osce.client.managed.ui.CheckListProxyRenderer.instance();

            @Override
            public String getValue(ChecklistTopicProxy object) {
                return renderer.render(object.getCheckList());
            }
        }, "Check List");
        paths.add("checkListQuestions");
        table.addColumn(new TextColumn<ChecklistTopicProxy>() {

            Renderer<java.util.List> renderer = ch.unibas.medizin.osce.client.scaffold.place.CollectionRenderer.of(ch.unibas.medizin.osce.client.managed.ui.ChecklistQuestionProxyRenderer.instance());

            @Override
            public String getValue(ChecklistTopicProxy object) {
                return renderer.render(object.getCheckListQuestions());
            }
        }, "Check List Questions");
        paths.add("description");
        table.addColumn(new TextColumn<ChecklistTopicProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(ChecklistTopicProxy object) {
                return renderer.render(object.getDescription());
            }
        }, "Description");
    }
}
