// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.ui;

import ch.unibas.medizin.osce.client.managed.request.AnamnesisCheckProxy;
import ch.unibas.medizin.osce.client.managed.request.EliminationCriterionProxy;
import ch.unibas.medizin.osce.client.managed.request.ScarProxy;
import ch.unibas.medizin.osce.client.managed.request.StandardizedRoleProxy;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyDetailsView;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class EliminationCriterionDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<EliminationCriterionProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    @UiField
    SpanElement anamnesisCheckValue;

    @UiField
    SpanElement standardizedRole;

    @UiField
    SpanElement scar;

    @UiField
    SpanElement anamnesisCheck;

    EliminationCriterionProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(EliminationCriterionProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        anamnesisCheckValue.setInnerText(proxy.getAnamnesisCheckValue() == null ? "" : String.valueOf(proxy.getAnamnesisCheckValue()));
        standardizedRole.setInnerText(proxy.getStandardizedRole() == null ? "" : ch.unibas.medizin.osce.client.managed.ui.StandardizedRoleProxyRenderer.instance().render(proxy.getStandardizedRole()));
        scar.setInnerText(proxy.getScar() == null ? "" : ch.unibas.medizin.osce.client.managed.ui.ScarProxyRenderer.instance().render(proxy.getScar()));
        anamnesisCheck.setInnerText(proxy.getAnamnesisCheck() == null ? "" : ch.unibas.medizin.osce.client.managed.ui.AnamnesisCheckProxyRenderer.instance().render(proxy.getAnamnesisCheck()));
        displayRenderer.setInnerText(EliminationCriterionProxyRenderer.instance().render(proxy));
    }
}
