// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.ui;

import ch.unibas.medizin.osce.client.managed.request.RoleBaseItemProxy;
import ch.unibas.medizin.osce.client.managed.request.RoleTemplateProxy;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyDetailsView;
import ch.unibas.medizin.osce.client.scaffold.place.ProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.List;

public abstract class RoleTemplateDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<RoleTemplateProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    @UiField
    SpanElement templateName;

    @UiField
    SpanElement date_cretaed;

    @UiField
    SpanElement date_edited;

    @UiField
    SpanElement roleBaseItem;

    RoleTemplateProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(RoleTemplateProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        templateName.setInnerText(proxy.getTemplateName() == null ? "" : String.valueOf(proxy.getTemplateName()));
        date_cretaed.setInnerText(proxy.getDate_cretaed() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_MEDIUM).format(proxy.getDate_cretaed()));
        date_edited.setInnerText(proxy.getDate_edited() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_MEDIUM).format(proxy.getDate_edited()));
        roleBaseItem.setInnerText(proxy.getRoleBaseItem() == null ? "" : ch.unibas.medizin.osce.client.scaffold.place.CollectionRenderer.of(ch.unibas.medizin.osce.client.managed.ui.RoleBaseItemProxyRenderer.instance()).render(proxy.getRoleBaseItem()));
        displayRenderer.setInnerText(RoleTemplateProxyRenderer.instance().render(proxy));
    }
}
