// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("ch.unibas.medizin.osce.domain.AnamnesisChecksValue")
@ServiceName("ch.unibas.medizin.osce.domain.AnamnesisChecksValue")
public interface AnamnesisChecksValueRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.AnamnesisChecksValueProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.AnamnesisChecksValueProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countAnamnesisChecksValues();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.AnamnesisChecksValueProxy>> findAllAnamnesisChecksValues();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.AnamnesisChecksValueProxy> findAnamnesisChecksValue(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.AnamnesisChecksValueProxy>> findAnamnesisChecksValueEntries(int firstResult, int maxResults);
}
