// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import java.util.List;

import com.google.web.bindery.requestfactory.shared.InstanceRequest;
import com.google.web.bindery.requestfactory.shared.Request;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.google.web.bindery.requestfactory.shared.ServiceName;

@ServiceName("ch.unibas.medizin.osce.domain.ChecklistCriteria")
public interface ChecklistCriteriaRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.ChecklistCriteriaProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.ChecklistCriteriaProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countChecklistCriterias();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.ChecklistCriteriaProxy> findChecklistCriteria(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.ChecklistCriteriaProxy>> findAllChecklistCriterias();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.ChecklistCriteriaProxy>> findChecklistCriteriaEntries(int firstResult, int maxResults);

	abstract Request<Boolean> updateSequence(List<ChecklistCriteriaProxy> ids);

	abstract Request<ChecklistItemProxy> saveChecklistCriteria(String name, String description, Long checklistItemId, Long checklistCriteriaId);
	
	abstract Request<ChecklistItemProxy> removeChecklistCriteria(Long criteriaId);
}
