// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("ch.unibas.medizin.osce.domain.Clinic")
@ServiceName("ch.unibas.medizin.osce.domain.Clinic")
public interface ClinicRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.ClinicProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.ClinicProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countClinics();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.ClinicProxy>> findAllClinics();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.ClinicProxy> findClinic(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.ClinicProxy>> findClinicEntries(int firstResult, int maxResults);
}
