// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import java.util.List;

import com.google.web.bindery.requestfactory.shared.InstanceRequest;
import com.google.web.bindery.requestfactory.shared.Request;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.google.web.bindery.requestfactory.shared.ServiceName;

@ServiceName("ch.unibas.medizin.osce.domain.Clinic")
public interface ClinicRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.ClinicProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.ClinicProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countClinics();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.ClinicProxy> findClinic(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.ClinicProxy>> findAllClinics();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.ClinicProxy>> findClinicEntries(int firstResult, int maxResults);
    
	abstract Request<Long> countClinicsBySearch(String q);
	
	abstract Request<Long> findSpecialist();
	
	abstract Request<List<ClinicProxy>> findAllDoctorsId(Long id);
	
	abstract Request<List<ClinicProxy>> findListOfDocsId(Long id);
	
	abstract Request<List<ClinicProxy>> findClinicsBySearch(String q, int firstResult, int maxResults);

}
