// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import ch.unibas.medizin.osce.shared.Gender;
import com.google.web.bindery.requestfactory.shared.EntityProxy;
import com.google.web.bindery.requestfactory.shared.ProxyForName;
import java.util.List;
import java.util.Set;

@ProxyForName("ch.unibas.medizin.osce.domain.Doctor")
public interface DoctorProxy extends EntityProxy {

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);

    abstract Gender getGender();

    abstract void setGender(Gender gender);

    abstract String getTitle();

    abstract void setTitle(String title);

    abstract String getName();

    abstract void setName(String name);

    abstract String getPreName();

    abstract void setPreName(String preName);

    abstract String getEmail();

    abstract void setEmail(String email);

    abstract String getTelephone();

    abstract void setTelephone(String telephone);

    abstract ClinicProxy getClinic();

    abstract void setClinic(ClinicProxy clinic);

    abstract OfficeProxy getOffice();

    abstract void setOffice(OfficeProxy office);

    abstract Boolean getIsActive();

    abstract void setIsActive(Boolean isActive);

    abstract SpecialisationProxy getSpecialisation();

    abstract void setSpecialisation(SpecialisationProxy specialisation);

    abstract Set<ch.unibas.medizin.osce.client.managed.request.AssignmentProxy> getAssignments();

    abstract void setAssignments(Set<AssignmentProxy> assignments);

    abstract Set<ch.unibas.medizin.osce.client.managed.request.RoleParticipantProxy> getRoleParticipants();

    abstract void setRoleParticipants(Set<RoleParticipantProxy> roleParticipants);

    abstract List<ch.unibas.medizin.osce.client.managed.request.PostAnalysisProxy> getPostAnalysis();

    abstract void setPostAnalysis(List<PostAnalysisProxy> postAnalysis);
}
