// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import java.util.List;

import ch.unibas.medizin.osce.shared.Sorting;

import com.google.web.bindery.requestfactory.shared.InstanceRequest;
import com.google.web.bindery.requestfactory.shared.Request;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.google.web.bindery.requestfactory.shared.ServiceName;

@ServiceName("ch.unibas.medizin.osce.domain.Doctor")
public interface DoctorRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.DoctorProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.DoctorProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countDoctors();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.DoctorProxy> findDoctor(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.DoctorProxy>> findAllDoctors();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.DoctorProxy>> findDoctorEntries(int firstResult, int maxResults);
    
    abstract Request<Long> countDoctorsBySearchWithClinic(String q,Long id);
	
	abstract Request<List<DoctorProxy>> findDoctorsBySearchWithClinic(String q,Long id, int firstResult, int maxResults, Sorting sortorder, String sortFiled);
	
	
	// SPEC START =
	abstract Request<List<DoctorProxy>> findDoctorWithRoleTopic(Long standroleid);
	// SPEC END =
	
	//Module 6 Start
	abstract Request<List<DoctorProxy>> findDoctorByClinicID(Long clinicid);
	//Module 6 End
	
	// Module10 Create plans
	abstract Request<List<DoctorProxy>> findDoctorByOsceId(Long doctorid);
	// E Module10 Create plans
		
	abstract Request<List<SpecialisationProxy>> findSpecialisationByClinicId(Long clinicId);
	
	abstract Request<List<DoctorProxy>> findDoctorByAssignment(Long specialisationId,Long clinicId);
	
	abstract Request<Void> updateExaminerIdToSession(List<Long> examiners);
}
