// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import java.util.List;

import com.google.web.bindery.requestfactory.shared.InstanceRequest;
import com.google.web.bindery.requestfactory.shared.Request;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.google.web.bindery.requestfactory.shared.ServiceName;

@ServiceName("ch.unibas.medizin.osce.domain.File")
public interface FileRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.FileProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.FileProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countFiles();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.FileProxy> findFile(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.FileProxy>> findAllFiles();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.FileProxy>> findFileEntries(int firstResult, int maxResults);

	abstract Request<Long> countFilesByName(String name);
	
	abstract Request<List<FileProxy>> findFileEntriesByName(String name, int firstResult, int maxResults);
	
	abstract Request<Long> countFilesByStandardizedRoleID(long standardizedRoleID);
	
	abstract Request<List<FileProxy>> findFileEntriesByStandardizedRoleID(long standardizedRoleID, int firstResult, int maxResults);
	
	public abstract InstanceRequest<FileProxy, Void> fileMoveUp(long standardizedRoleID);
	public abstract InstanceRequest<FileProxy, Void> fileMoveDown(long standardizedRoleID);
	public abstract Request<FileProxy> findFilesByOrderSmaller(long standardizedRoleID,int sort_order);
	public abstract Request<FileProxy> findFilesByOrderGreater(long standardizedRoleID,int sort_order);


}
