// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.web.bindery.requestfactory.shared.InstanceRequest;
import com.google.web.bindery.requestfactory.shared.Request;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.google.web.bindery.requestfactory.shared.ServiceName;

@ServiceName("ch.unibas.medizin.osce.domain.ItemAnalysis")
public interface ItemAnalysisRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.ItemAnalysisProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.ItemAnalysisProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countItemAnalyses();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.ItemAnalysisProxy> findItemAnalysis(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.ItemAnalysisProxy>> findAllItemAnalyses();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.ItemAnalysisProxy>> findItemAnalysisEntries(int firstResult, int maxResults);

    abstract Request<Boolean>  deActivateItem(Long osceId,Long itemId,Boolean deActivate);

}
