// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.web.bindery.requestfactory.shared.EntityProxy;
import com.google.web.bindery.requestfactory.shared.ProxyForName;
import java.util.Date;

@ProxyForName("ch.unibas.medizin.osce.domain.KeyPair")
public interface KeyPairProxy extends EntityProxy {

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);

    abstract String getPrivateKey();

    abstract void setPrivateKey(String privateKey);

    abstract String getPublicKey();

    abstract void setPublicKey(String publicKey);

    abstract Date getDate();

    abstract void setDate(Date date);

    abstract Long getUserId();

    abstract void setUserId(Long userId);

    abstract Boolean getActive();

    abstract void setActive(Boolean active);
}
