// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("ch.unibas.medizin.osce.domain.LangSkill")
@ServiceName("ch.unibas.medizin.osce.domain.LangSkill")
public interface LangSkillRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.LangSkillProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.LangSkillProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countLangSkills();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.LangSkillProxy>> findAllLangSkills();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.LangSkillProxy> findLangSkill(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.LangSkillProxy>> findLangSkillEntries(int firstResult, int maxResults);
}
