// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import java.util.List;

import com.google.web.bindery.requestfactory.shared.InstanceRequest;
import com.google.web.bindery.requestfactory.shared.Request;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.google.web.bindery.requestfactory.shared.ServiceName;

@ServiceName("ch.unibas.medizin.osce.domain.Nationality")
public interface NationalityRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.NationalityProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.NationalityProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countNationalitys();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.NationalityProxy> findNationality(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.NationalityProxy>> findAllNationalitys();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.NationalityProxy>> findNationalityEntries(int firstResult, int maxResults);

    abstract Request<Long> countNationalitiesByName(String name);
	
	abstract Request<List<NationalityProxy>> findNationalitiesByName(String name, int firstResult, int maxResults);
	
	abstract Request<Integer> checkNationnality(String name);

	abstract Request<Boolean> saveNationalityInSpPortal(NationalityProxy nation);

	abstract Request<Boolean> editNationalityInSpPortal(NationalityProxy nation,String value);

	abstract Request<Boolean> deleteNatinalityInSpPortal(NationalityProxy nation);
}
