// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import ch.unibas.medizin.osce.shared.Gender;
import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("ch.unibas.medizin.osce.domain.Office")
@ProxyForName("ch.unibas.medizin.osce.domain.Office")
public interface OfficeProxy extends EntityProxy {

    abstract Gender getGender();

    abstract void setGender(Gender gender);

    abstract String getTitle();

    abstract void setTitle(String title);

    abstract String getName();

    abstract void setName(String name);

    abstract String getPreName();

    abstract void setPreName(String preName);

    abstract String getEmail();

    abstract void setEmail(String email);

    abstract String getTelephone();

    abstract void setTelephone(String telephone);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);
}
