// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.web.bindery.requestfactory.shared.EntityProxy;
import com.google.web.bindery.requestfactory.shared.ProxyForName;
import java.util.List;
import java.util.Set;

@ProxyForName("ch.unibas.medizin.osce.domain.OscePost")
public interface OscePostProxy extends EntityProxy {

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);

    abstract OscePostBlueprintProxy getOscePostBlueprint();

    abstract void setOscePostBlueprint(OscePostBlueprintProxy oscePostBlueprint);

    abstract Set<ch.unibas.medizin.osce.client.managed.request.OscePostRoomProxy> getOscePostRooms();

    abstract void setOscePostRooms(Set<OscePostRoomProxy> oscePostRooms);

    abstract Set<ch.unibas.medizin.osce.client.managed.request.PatientInRoleProxy> getPatientInRole();

    abstract void setPatientInRole(Set<PatientInRoleProxy> patientInRole);

    abstract StandardizedRoleProxy getStandardizedRole();

    abstract void setStandardizedRole(StandardizedRoleProxy standardizedRole);

    abstract OsceSequenceProxy getOsceSequence();

    abstract void setOsceSequence(OsceSequenceProxy osceSequence);

    abstract Integer getSequenceNumber();

    abstract void setSequenceNumber(Integer sequenceNumber);

    abstract Integer getValue();

    abstract void setValue(Integer value);

    abstract List<ch.unibas.medizin.osce.client.managed.request.ItemAnalysisProxy> getItemAnalysis();

    abstract void setItemAnalysis(List<ItemAnalysisProxy> itemAnalysis);

    abstract List<ch.unibas.medizin.osce.client.managed.request.PostAnalysisProxy> getPostAnalysis();

    abstract void setPostAnalysis(List<PostAnalysisProxy> postAnalysis);
}
