// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.web.bindery.requestfactory.shared.InstanceRequest;
import com.google.web.bindery.requestfactory.shared.Request;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.google.web.bindery.requestfactory.shared.ServiceName;

@ServiceName("ch.unibas.medizin.osce.domain.PostAnalysis")
public interface PostAnalysisRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.PostAnalysisProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.PostAnalysisProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countPostAnalyses();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.PostAnalysisProxy> findPostAnalysis(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.PostAnalysisProxy>> findAllPostAnalyses();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.PostAnalysisProxy>> findPostAnalysisEntries(int firstResult, int maxResults);
}
