// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("ch.unibas.medizin.osce.domain.RoleParticipant")
@ServiceName("ch.unibas.medizin.osce.domain.RoleParticipant")
public interface RoleParticipantRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.RoleParticipantProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.RoleParticipantProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countRoleParticipants();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.RoleParticipantProxy>> findAllRoleParticipants();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.RoleParticipantProxy> findRoleParticipant(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.RoleParticipantProxy>> findRoleParticipantEntries(int firstResult, int maxResults);
}
