// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("ch.unibas.medizin.osce.domain.RoleSubItemValue")
@ServiceName("ch.unibas.medizin.osce.domain.RoleSubItemValue")
public interface RoleSubItemValueRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.RoleSubItemValueProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.RoleSubItemValueProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countRoleSubItemValues();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.RoleSubItemValueProxy> findRoleSubItemValue(Integer id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.RoleSubItemValueProxy>> findAllRoleSubItemValues();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.RoleSubItemValueProxy>> findRoleSubItemValueEntries(int firstResult, int maxResults);
}
