// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.web.bindery.requestfactory.shared.EntityProxy;
import com.google.web.bindery.requestfactory.shared.ProxyForName;
import java.util.Date;
import java.util.Set;

@ProxyForName("ch.unibas.medizin.osce.domain.spportal.SpAnamnesisForm")
public interface SpAnamnesisFormProxy extends EntityProxy {

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);

    abstract Date getCreateDate();

    abstract void setCreateDate(Date createDate);

    abstract Set<ch.unibas.medizin.osce.client.managed.request.SpAnamnesisChecksValueProxy> getAnamnesischecksvalues();

    abstract void setAnamnesischecksvalues(Set<SpAnamnesisChecksValueProxy> anamnesischecksvalues);

    abstract Set<ch.unibas.medizin.osce.client.managed.request.SpScarProxy> getScars();

    abstract void setScars(Set<SpScarProxy> scars);
}
