// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import ch.unibas.medizin.osce.shared.TraitTypes;
import com.google.web.bindery.requestfactory.shared.EntityProxy;
import com.google.web.bindery.requestfactory.shared.ProxyForName;
import java.util.Set;

@ProxyForName("ch.unibas.medizin.osce.domain.spportal.SpScar")
public interface SpScarProxy extends EntityProxy {

    abstract Long getId();

    abstract void setId(Long id);

    abstract Integer getVersion();

    abstract void setVersion(Integer version);

    abstract String getBodypart();

    abstract void setBodypart(String bodypart);

    abstract TraitTypes getTraitType();

    abstract void setTraitType(TraitTypes traitType);

    abstract Set<ch.unibas.medizin.osce.client.managed.request.SpAnamnesisFormProxy> getAnamnesisForms();

    abstract void setAnamnesisForms(Set<SpAnamnesisFormProxy> anamnesisForms);
}
