// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.web.bindery.requestfactory.shared.InstanceRequest;
import com.google.web.bindery.requestfactory.shared.Request;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.google.web.bindery.requestfactory.shared.ServiceName;

@ServiceName("ch.unibas.medizin.osce.domain.spportal.SpSemester")
public interface SpSemesterRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.SpSemesterProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.SpSemesterProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countSpSemesters();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.SpSemesterProxy> findSpSemester(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.SpSemesterProxy>> findAllSpSemesters();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.SpSemesterProxy>> findSpSemesterEntries(int firstResult, int maxResults);
}
