// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.web.bindery.requestfactory.shared.EntityProxy;
import com.google.web.bindery.requestfactory.shared.ProxyForName;
import java.util.Date;
import java.util.Set;

@ProxyForName("ch.unibas.medizin.osce.domain.spportal.SpTrainingDate")
public interface SpTrainingDateProxy extends EntityProxy {

    abstract Integer getVersion();

    abstract void setVersion(Integer version);

    abstract Long getId();

    abstract void setId(Long id);

    abstract Date getTrainingDate();

    abstract void setTrainingDate(Date trainingDate);

    abstract Boolean getIsAfternoon();

    abstract void setIsAfternoon(Boolean isAfternoon);

    abstract SpTrainingBlockProxy getTrainingBlock();

    abstract void setTrainingBlock(SpTrainingBlockProxy trainingBlock);

    abstract Set<ch.unibas.medizin.osce.client.managed.request.SpPatientInSemesterProxy> getPatientInSemesters();

    abstract void setPatientInSemesters(Set<SpPatientInSemesterProxy> patientInSemesters);
}
