// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("ch.unibas.medizin.osce.domain.StandardizedPatient")
@ServiceName("ch.unibas.medizin.osce.domain.StandardizedPatient")
public interface StandardizedPatientRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.StandardizedPatientProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.StandardizedPatientProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countStandardizedPatients();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.StandardizedPatientProxy>> findAllStandardizedPatients();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.StandardizedPatientProxy> findStandardizedPatient(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.StandardizedPatientProxy>> findStandardizedPatientEntries(int firstResult, int maxResults);
}
