// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("ch.unibas.medizin.osce.domain.Task")
@ServiceName("ch.unibas.medizin.osce.domain.Task")
public interface TaskRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.TaskProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.TaskProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countTasks();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.TaskProxy>> findAllTasks();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.TaskProxy> findTask(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.TaskProxy>> findTaskEntries(int firstResult, int maxResults);
}
