// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.medizin.osce.client.managed.request;

import java.util.List;

import com.google.web.bindery.requestfactory.shared.InstanceRequest;
import com.google.web.bindery.requestfactory.shared.Request;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import com.google.web.bindery.requestfactory.shared.ServiceName;

@ServiceName("ch.unibas.medizin.osce.domain.UsedMaterial")
public interface UsedMaterialRequest extends RequestContext {

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.UsedMaterialProxy, java.lang.Void> persist();

    abstract InstanceRequest<ch.unibas.medizin.osce.client.managed.request.UsedMaterialProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countUsedMaterials();

    abstract Request<ch.unibas.medizin.osce.client.managed.request.UsedMaterialProxy> findUsedMaterial(Long id);

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.UsedMaterialProxy>> findAllUsedMaterials();

    abstract Request<java.util.List<ch.unibas.medizin.osce.client.managed.request.UsedMaterialProxy>> findUsedMaterialEntries(int firstResult, int maxResults);

	abstract InstanceRequest<UsedMaterialProxy, Void> moveMaterialUp(
			long standardizedRoleID);

	abstract InstanceRequest<UsedMaterialProxy, Void> moveMaterialDown(
			long standardizedRoleID);

	abstract Request<UsedMaterialProxy> findUsedMaterialByOrderSmaller(
			long standardizedRoleID, int sort_order);

	abstract Request<UsedMaterialProxy> findUsedMaterialByOrderGreater(
			long standardizedRoleID, int sort_order);

	abstract Request<Long> countUsedMaterialsByStandardizedRoleID(long standardizedRoleID);

	abstract Request<List<UsedMaterialProxy>> findUsedMaterialsByStandardizedRoleID(long standardizedRoleID, int firstResult, int maxResults);
	
	abstract Request<List<UsedMaterialProxy>> findUsedMaterialsByStandardizedRoleIDpdf(long standardizedRoleID);

}
